#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "**** Setup complete, starting Janus ****"

if [[ -z "${LSIO_NON_ROOT_USER:-}" ]]; then
    RUN_USER="abc"
else
    RUN_USER="www-data"
fi

cd /app

# Read PORT from the app's .env (written by init-janus-config), fall back to env.
# shellcheck disable=SC1091
. /config/.env 2>/dev/null || true
PORT="${PORT:-3000}"

exec \
    s6-setuidgid "${RUN_USER}" node dist/main
